### ISSUE TITLE
Dockerfile provision as part of codebase

### ISSUE THREAD

**Issue by jancajthaml** [slesinger/czech-speech-to-text#2]
Hey :)

Love that someone is finally doing that, we have usecase where we do pure transcript from Czech audio to voices and are currently using google speech recognition api (works good but not ideal for our usecases).

We are looking for fully offline solution, would it be possible to update your codebase with provisioning of docker (Dockerfile and all the required binaries to run the server).

I think that what you are refering to in readme is something like this https://github.com/arpabet/deepspeech-docker/blob/master/Dockerfile .

Thanks

**Comment by slesinger** [comment]
I have added a link to readme. Thank you. Diky.
